create_clock -period 10.000 -name sys_clk [get_pins -match_style ucf */pcieclk_ibuf/O]

set_false_path -to [get_pins -match_style ucf */pipe_clock/pclk_i1_bufgctrl.pclk_i1/S0]
set_false_path -to [get_pins -match_style ucf */pipe_clock/pclk_i1_bufgctrl.pclk_i1/S1]
set_case_analysis 1 [get_pins -match_style ucf */pipe_clock/pclk_i1_bufgctrl.pclk_i1/S0]
set_case_analysis 0 [get_pins -match_style ucf */pipe_clock/pclk_i1_bufgctrl.pclk_i1/S1]

set_property DONT_TOUCH true [get_cells -of [get_nets -of [get_pins -match_style ucf */pipe_clock/pclk_i1_bufgctrl.pclk_i1/S0]]]
set_property DONT_TOUCH true [get_cells -hier -filter name=~*/pipe_clock/pclk_sel*]

set_false_path -from [get_ports PCIE_PERST_B_LS]

set_property LOC IBUFDS_GTE2_X1Y5 [get_cells xillybus_ins/pcieclk_ibuf]

set_property PACKAGE_PIN AV35 [get_ports PCIE_PERST_B_LS]
set_property IOSTANDARD LVCMOS18 [get_ports PCIE_PERST_B_LS]
set_property PULLUP true [get_ports PCIE_PERST_B_LS]

set_property PACKAGE_PIN AM39 [get_ports {GPIO_LED[0]}]
set_property IOSTANDARD LVCMOS18 [get_ports {GPIO_LED[0]}]
set_property PACKAGE_PIN AN39 [get_ports {GPIO_LED[1]}]
set_property IOSTANDARD LVCMOS18 [get_ports {GPIO_LED[1]}]
set_property PACKAGE_PIN AR37 [get_ports {GPIO_LED[2]}]
set_property IOSTANDARD LVCMOS18 [get_ports {GPIO_LED[2]}]
set_property PACKAGE_PIN AT37 [get_ports {GPIO_LED[3]}]
set_property IOSTANDARD LVCMOS18 [get_ports {GPIO_LED[3]}]

set_property MARK_DEBUG true [get_nets {cpcie_bd_wrapper_i/cpcie_bd_i/scheduler_cpcie_0/status_engine_1[25]}]
set_property MARK_DEBUG true [get_nets {cpcie_bd_wrapper_i/cpcie_bd_i/scheduler_cpcie_0/status_engine_0[25]}]
set_property MARK_DEBUG true [get_nets {cpcie_bd_wrapper_i/cpcie_bd_i/scheduler_cpcie_0/status_engine_1[21]}]
set_property MARK_DEBUG true [get_nets {cpcie_bd_wrapper_i/cpcie_bd_i/scheduler_cpcie_0/status_engine_1[17]}]
set_property MARK_DEBUG true [get_nets {cpcie_bd_wrapper_i/cpcie_bd_i/scheduler_cpcie_0/status_engine_0[30]}]
set_property MARK_DEBUG true [get_nets {cpcie_bd_wrapper_i/cpcie_bd_i/scheduler_cpcie_0/status_engine_1[26]}]
set_property MARK_DEBUG true [get_nets {cpcie_bd_wrapper_i/cpcie_bd_i/scheduler_cpcie_0/status_engine_0[26]}]
set_property MARK_DEBUG true [get_nets {cpcie_bd_wrapper_i/cpcie_bd_i/scheduler_cpcie_0/status_engine_1[9]}]
set_property MARK_DEBUG true [get_nets {cpcie_bd_wrapper_i/cpcie_bd_i/scheduler_cpcie_0/status_engine_1[22]}]
set_property MARK_DEBUG true [get_nets {cpcie_bd_wrapper_i/cpcie_bd_i/scheduler_cpcie_0/status_engine_1[24]}]
set_property MARK_DEBUG true [get_nets {cpcie_bd_wrapper_i/cpcie_bd_i/scheduler_cpcie_0/status_engine_0[24]}]
set_property MARK_DEBUG true [get_nets {cpcie_bd_wrapper_i/cpcie_bd_i/scheduler_cpcie_0/status_engine_1[27]}]
set_property MARK_DEBUG true [get_nets {cpcie_bd_wrapper_i/cpcie_bd_i/scheduler_cpcie_0/status_engine_0[27]}]
set_property MARK_DEBUG true [get_nets {cpcie_bd_wrapper_i/cpcie_bd_i/scheduler_cpcie_0/status_engine_1[23]}]
set_property MARK_DEBUG true [get_nets {cpcie_bd_wrapper_i/cpcie_bd_i/scheduler_cpcie_0/status_engine_0[29]}]
set_property MARK_DEBUG true [get_nets {cpcie_bd_wrapper_i/cpcie_bd_i/scheduler_cpcie_0/status_engine_0[31]}]
set_property MARK_DEBUG true [get_nets {cpcie_bd_wrapper_i/cpcie_bd_i/scheduler_cpcie_0/status_engine_1[0]}]
set_property MARK_DEBUG true [get_nets {cpcie_bd_wrapper_i/cpcie_bd_i/scheduler_cpcie_0/status_engine_1[1]}]
set_property MARK_DEBUG true [get_nets {cpcie_bd_wrapper_i/cpcie_bd_i/scheduler_cpcie_0/status_engine_1[2]}]
set_property MARK_DEBUG true [get_nets {cpcie_bd_wrapper_i/cpcie_bd_i/scheduler_cpcie_0/status_engine_1[3]}]
set_property MARK_DEBUG true [get_nets {cpcie_bd_wrapper_i/cpcie_bd_i/scheduler_cpcie_0/status_engine_1[5]}]
set_property MARK_DEBUG true [get_nets {cpcie_bd_wrapper_i/cpcie_bd_i/scheduler_cpcie_0/status_engine_1[6]}]
set_property MARK_DEBUG true [get_nets {cpcie_bd_wrapper_i/cpcie_bd_i/scheduler_cpcie_0/status_engine_1[7]}]
set_property MARK_DEBUG true [get_nets {cpcie_bd_wrapper_i/cpcie_bd_i/scheduler_cpcie_0/status_engine_1[4]}]
set_property MARK_DEBUG true [get_nets {cpcie_bd_wrapper_i/cpcie_bd_i/scheduler_cpcie_0/status_engine_1[8]}]
set_property MARK_DEBUG true [get_nets {cpcie_bd_wrapper_i/cpcie_bd_i/scheduler_cpcie_0/status_engine_1[11]}]
set_property MARK_DEBUG true [get_nets {cpcie_bd_wrapper_i/cpcie_bd_i/scheduler_cpcie_0/status_engine_1[10]}]
set_property MARK_DEBUG true [get_nets {cpcie_bd_wrapper_i/cpcie_bd_i/scheduler_cpcie_0/status_engine_1[12]}]
set_property MARK_DEBUG true [get_nets {cpcie_bd_wrapper_i/cpcie_bd_i/scheduler_cpcie_0/status_engine_1[13]}]
set_property MARK_DEBUG true [get_nets {cpcie_bd_wrapper_i/cpcie_bd_i/scheduler_cpcie_0/status_engine_1[14]}]
set_property MARK_DEBUG true [get_nets {cpcie_bd_wrapper_i/cpcie_bd_i/scheduler_cpcie_0/status_engine_1[15]}]
set_property MARK_DEBUG true [get_nets {cpcie_bd_wrapper_i/cpcie_bd_i/scheduler_cpcie_0/status_engine_1[16]}]
set_property MARK_DEBUG true [get_nets {cpcie_bd_wrapper_i/cpcie_bd_i/scheduler_cpcie_0/status_engine_1[18]}]
set_property MARK_DEBUG true [get_nets {cpcie_bd_wrapper_i/cpcie_bd_i/scheduler_cpcie_0/status_engine_1[19]}]
set_property MARK_DEBUG true [get_nets {cpcie_bd_wrapper_i/cpcie_bd_i/scheduler_cpcie_0/status_engine_1[20]}]
set_property MARK_DEBUG true [get_nets {cpcie_bd_wrapper_i/cpcie_bd_i/scheduler_cpcie_0/status_engine_1[28]}]
set_property MARK_DEBUG true [get_nets {cpcie_bd_wrapper_i/cpcie_bd_i/scheduler_cpcie_0/status_engine_2[15]}]
set_property MARK_DEBUG true [get_nets {cpcie_bd_wrapper_i/cpcie_bd_i/scheduler_cpcie_0/status_engine_2[7]}]
set_property MARK_DEBUG true [get_nets {cpcie_bd_wrapper_i/cpcie_bd_i/scheduler_cpcie_0/status_engine_2[27]}]
set_property MARK_DEBUG true [get_nets {cpcie_bd_wrapper_i/cpcie_bd_i/scheduler_cpcie_0/status_engine_3[13]}]
set_property MARK_DEBUG true [get_nets {cpcie_bd_wrapper_i/cpcie_bd_i/scheduler_cpcie_0/status_engine_3[19]}]
set_property MARK_DEBUG true [get_nets {cpcie_bd_wrapper_i/cpcie_bd_i/scheduler_cpcie_0/status_engine_3[7]}]
set_property MARK_DEBUG true [get_nets {cpcie_bd_wrapper_i/cpcie_bd_i/scheduler_cpcie_0/status_engine_2[25]}]
set_property MARK_DEBUG true [get_nets {cpcie_bd_wrapper_i/cpcie_bd_i/scheduler_cpcie_0/status_engine_2[29]}]
set_property MARK_DEBUG true [get_nets {cpcie_bd_wrapper_i/cpcie_bd_i/scheduler_cpcie_0/status_engine_0[2]}]
set_property MARK_DEBUG true [get_nets {cpcie_bd_wrapper_i/cpcie_bd_i/scheduler_cpcie_0/status_engine_0[0]}]
set_property MARK_DEBUG true [get_nets {cpcie_bd_wrapper_i/cpcie_bd_i/scheduler_cpcie_0/status_engine_3[31]}]
set_property MARK_DEBUG true [get_nets {cpcie_bd_wrapper_i/cpcie_bd_i/scheduler_cpcie_0/status_engine_3[25]}]
set_property MARK_DEBUG true [get_nets {cpcie_bd_wrapper_i/cpcie_bd_i/scheduler_cpcie_0/status_engine_3[10]}]
set_property MARK_DEBUG true [get_nets {cpcie_bd_wrapper_i/cpcie_bd_i/scheduler_cpcie_0/status_engine_2[17]}]
set_property MARK_DEBUG true [get_nets {cpcie_bd_wrapper_i/cpcie_bd_i/scheduler_cpcie_0/status_engine_3[23]}]
set_property MARK_DEBUG true [get_nets {cpcie_bd_wrapper_i/cpcie_bd_i/scheduler_cpcie_0/status_engine_2[5]}]
set_property MARK_DEBUG true [get_nets {cpcie_bd_wrapper_i/cpcie_bd_i/scheduler_cpcie_0/status_engine_2[10]}]
set_property MARK_DEBUG true [get_nets {cpcie_bd_wrapper_i/cpcie_bd_i/scheduler_cpcie_0/status_engine_1[29]}]
set_property MARK_DEBUG true [get_nets {cpcie_bd_wrapper_i/cpcie_bd_i/scheduler_cpcie_0/status_engine_2[14]}]
set_property MARK_DEBUG true [get_nets {cpcie_bd_wrapper_i/cpcie_bd_i/scheduler_cpcie_0/status_engine_2[21]}]
set_property MARK_DEBUG true [get_nets {cpcie_bd_wrapper_i/cpcie_bd_i/scheduler_cpcie_0/status_engine_3[22]}]
set_property MARK_DEBUG true [get_nets {cpcie_bd_wrapper_i/cpcie_bd_i/scheduler_cpcie_0/status_engine_2[31]}]
set_property MARK_DEBUG true [get_nets {cpcie_bd_wrapper_i/cpcie_bd_i/scheduler_cpcie_0/status_engine_0[28]}]
set_property MARK_DEBUG true [get_nets {cpcie_bd_wrapper_i/cpcie_bd_i/scheduler_cpcie_0/status_engine_3[11]}]
set_property MARK_DEBUG true [get_nets {cpcie_bd_wrapper_i/cpcie_bd_i/scheduler_cpcie_0/status_engine_2[23]}]
set_property MARK_DEBUG true [get_nets {cpcie_bd_wrapper_i/cpcie_bd_i/scheduler_cpcie_0/status_engine_1[31]}]
set_property MARK_DEBUG true [get_nets {cpcie_bd_wrapper_i/cpcie_bd_i/scheduler_cpcie_0/status_engine_2[1]}]
set_property MARK_DEBUG true [get_nets {cpcie_bd_wrapper_i/cpcie_bd_i/scheduler_cpcie_0/status_engine_0[23]}]
set_property MARK_DEBUG true [get_nets {cpcie_bd_wrapper_i/cpcie_bd_i/scheduler_cpcie_0/status_engine_0[8]}]
set_property MARK_DEBUG true [get_nets {cpcie_bd_wrapper_i/cpcie_bd_i/scheduler_cpcie_0/status_engine_0[22]}]
set_property MARK_DEBUG true [get_nets {cpcie_bd_wrapper_i/cpcie_bd_i/scheduler_cpcie_0/status_engine_0[16]}]
set_property MARK_DEBUG true [get_nets {cpcie_bd_wrapper_i/cpcie_bd_i/scheduler_cpcie_0/status_engine_3[17]}]
set_property MARK_DEBUG true [get_nets {cpcie_bd_wrapper_i/cpcie_bd_i/scheduler_cpcie_0/status_engine_3[16]}]
set_property MARK_DEBUG true [get_nets {cpcie_bd_wrapper_i/cpcie_bd_i/scheduler_cpcie_0/status_engine_0[9]}]
set_property MARK_DEBUG true [get_nets {cpcie_bd_wrapper_i/cpcie_bd_i/scheduler_cpcie_0/status_engine_2[11]}]
set_property MARK_DEBUG true [get_nets {cpcie_bd_wrapper_i/cpcie_bd_i/scheduler_cpcie_0/status_engine_0[14]}]
set_property MARK_DEBUG true [get_nets {cpcie_bd_wrapper_i/cpcie_bd_i/scheduler_cpcie_0/status_engine_3[1]}]
set_property MARK_DEBUG true [get_nets {cpcie_bd_wrapper_i/cpcie_bd_i/scheduler_cpcie_0/status_engine_3[28]}]
set_property MARK_DEBUG true [get_nets {cpcie_bd_wrapper_i/cpcie_bd_i/scheduler_cpcie_0/status_engine_3[26]}]
set_property MARK_DEBUG true [get_nets {cpcie_bd_wrapper_i/cpcie_bd_i/scheduler_cpcie_0/status_engine_0[18]}]
set_property MARK_DEBUG true [get_nets {cpcie_bd_wrapper_i/cpcie_bd_i/scheduler_cpcie_0/status_engine_0[4]}]
set_property MARK_DEBUG true [get_nets {cpcie_bd_wrapper_i/cpcie_bd_i/scheduler_cpcie_0/status_engine_2[13]}]
set_property MARK_DEBUG true [get_nets {cpcie_bd_wrapper_i/cpcie_bd_i/scheduler_cpcie_0/status_engine_2[19]}]
set_property MARK_DEBUG true [get_nets {cpcie_bd_wrapper_i/cpcie_bd_i/scheduler_cpcie_0/status_engine_0[6]}]
set_property MARK_DEBUG true [get_nets {cpcie_bd_wrapper_i/cpcie_bd_i/scheduler_cpcie_0/status_engine_0[12]}]
set_property MARK_DEBUG true [get_nets {cpcie_bd_wrapper_i/cpcie_bd_i/scheduler_cpcie_0/status_engine_0[20]}]
set_property MARK_DEBUG true [get_nets {cpcie_bd_wrapper_i/cpcie_bd_i/scheduler_cpcie_0/status_engine_2[3]}]
set_property MARK_DEBUG true [get_nets {cpcie_bd_wrapper_i/cpcie_bd_i/scheduler_cpcie_0/status_engine_3[3]}]
set_property MARK_DEBUG true [get_nets {cpcie_bd_wrapper_i/cpcie_bd_i/scheduler_cpcie_0/status_engine_3[5]}]
set_property MARK_DEBUG true [get_nets {cpcie_bd_wrapper_i/cpcie_bd_i/scheduler_cpcie_0/status_engine_3[15]}]
set_property MARK_DEBUG true [get_nets {cpcie_bd_wrapper_i/cpcie_bd_i/scheduler_cpcie_0/status_engine_3[21]}]
set_property MARK_DEBUG true [get_nets {cpcie_bd_wrapper_i/cpcie_bd_i/scheduler_cpcie_0/status_engine_3[27]}]
set_property MARK_DEBUG true [get_nets {cpcie_bd_wrapper_i/cpcie_bd_i/scheduler_cpcie_0/status_engine_3[29]}]
set_property MARK_DEBUG true [get_nets {cpcie_bd_wrapper_i/cpcie_bd_i/scheduler_cpcie_0/status_engine_2[4]}]
set_property MARK_DEBUG true [get_nets {cpcie_bd_wrapper_i/cpcie_bd_i/scheduler_cpcie_0/status_engine_2[9]}]
set_property MARK_DEBUG true [get_nets {cpcie_bd_wrapper_i/cpcie_bd_i/scheduler_cpcie_0/status_engine_2[20]}]
set_property MARK_DEBUG true [get_nets {cpcie_bd_wrapper_i/cpcie_bd_i/scheduler_cpcie_0/status_engine_0[5]}]
set_property MARK_DEBUG true [get_nets {cpcie_bd_wrapper_i/cpcie_bd_i/scheduler_cpcie_0/status_engine_0[15]}]
set_property MARK_DEBUG true [get_nets {cpcie_bd_wrapper_i/cpcie_bd_i/scheduler_cpcie_0/status_engine_2[6]}]
set_property MARK_DEBUG true [get_nets {cpcie_bd_wrapper_i/cpcie_bd_i/scheduler_cpcie_0/status_engine_0[1]}]
set_property MARK_DEBUG true [get_nets {cpcie_bd_wrapper_i/cpcie_bd_i/scheduler_cpcie_0/status_engine_0[3]}]
set_property MARK_DEBUG true [get_nets {cpcie_bd_wrapper_i/cpcie_bd_i/scheduler_cpcie_0/status_engine_0[7]}]
set_property MARK_DEBUG true [get_nets {cpcie_bd_wrapper_i/cpcie_bd_i/scheduler_cpcie_0/status_engine_0[11]}]
set_property MARK_DEBUG true [get_nets {cpcie_bd_wrapper_i/cpcie_bd_i/scheduler_cpcie_0/status_engine_0[10]}]
set_property MARK_DEBUG true [get_nets {cpcie_bd_wrapper_i/cpcie_bd_i/scheduler_cpcie_0/status_engine_0[13]}]
set_property MARK_DEBUG true [get_nets {cpcie_bd_wrapper_i/cpcie_bd_i/scheduler_cpcie_0/status_engine_0[17]}]
set_property MARK_DEBUG true [get_nets {cpcie_bd_wrapper_i/cpcie_bd_i/scheduler_cpcie_0/status_engine_0[19]}]
set_property MARK_DEBUG true [get_nets {cpcie_bd_wrapper_i/cpcie_bd_i/scheduler_cpcie_0/status_engine_0[21]}]
set_property MARK_DEBUG true [get_nets {cpcie_bd_wrapper_i/cpcie_bd_i/scheduler_cpcie_0/status_engine_1[30]}]
set_property MARK_DEBUG true [get_nets {cpcie_bd_wrapper_i/cpcie_bd_i/scheduler_cpcie_0/status_engine_2[0]}]
set_property MARK_DEBUG true [get_nets {cpcie_bd_wrapper_i/cpcie_bd_i/scheduler_cpcie_0/status_engine_2[2]}]
set_property MARK_DEBUG true [get_nets {cpcie_bd_wrapper_i/cpcie_bd_i/scheduler_cpcie_0/status_engine_2[8]}]
set_property MARK_DEBUG true [get_nets {cpcie_bd_wrapper_i/cpcie_bd_i/scheduler_cpcie_0/status_engine_2[12]}]
set_property MARK_DEBUG true [get_nets {cpcie_bd_wrapper_i/cpcie_bd_i/scheduler_cpcie_0/status_engine_2[16]}]
set_property MARK_DEBUG true [get_nets {cpcie_bd_wrapper_i/cpcie_bd_i/scheduler_cpcie_0/status_engine_2[18]}]
set_property MARK_DEBUG true [get_nets {cpcie_bd_wrapper_i/cpcie_bd_i/scheduler_cpcie_0/status_engine_2[22]}]
set_property MARK_DEBUG true [get_nets {cpcie_bd_wrapper_i/cpcie_bd_i/scheduler_cpcie_0/status_engine_2[24]}]
set_property MARK_DEBUG true [get_nets {cpcie_bd_wrapper_i/cpcie_bd_i/scheduler_cpcie_0/status_engine_2[26]}]
set_property MARK_DEBUG true [get_nets {cpcie_bd_wrapper_i/cpcie_bd_i/scheduler_cpcie_0/status_engine_2[30]}]
set_property MARK_DEBUG true [get_nets {cpcie_bd_wrapper_i/cpcie_bd_i/scheduler_cpcie_0/status_engine_3[2]}]
set_property MARK_DEBUG true [get_nets {cpcie_bd_wrapper_i/cpcie_bd_i/scheduler_cpcie_0/status_engine_3[4]}]
set_property MARK_DEBUG true [get_nets {cpcie_bd_wrapper_i/cpcie_bd_i/scheduler_cpcie_0/status_engine_3[6]}]
set_property MARK_DEBUG true [get_nets {cpcie_bd_wrapper_i/cpcie_bd_i/scheduler_cpcie_0/status_engine_3[9]}]
set_property MARK_DEBUG true [get_nets {cpcie_bd_wrapper_i/cpcie_bd_i/scheduler_cpcie_0/status_engine_3[18]}]
set_property MARK_DEBUG true [get_nets {cpcie_bd_wrapper_i/cpcie_bd_i/scheduler_cpcie_0/status_engine_2[28]}]
set_property MARK_DEBUG true [get_nets {cpcie_bd_wrapper_i/cpcie_bd_i/scheduler_cpcie_0/status_engine_3[0]}]
set_property MARK_DEBUG true [get_nets {cpcie_bd_wrapper_i/cpcie_bd_i/scheduler_cpcie_0/status_engine_3[8]}]
set_property MARK_DEBUG true [get_nets {cpcie_bd_wrapper_i/cpcie_bd_i/scheduler_cpcie_0/status_engine_3[12]}]
set_property MARK_DEBUG true [get_nets {cpcie_bd_wrapper_i/cpcie_bd_i/scheduler_cpcie_0/status_engine_3[14]}]
set_property MARK_DEBUG true [get_nets {cpcie_bd_wrapper_i/cpcie_bd_i/scheduler_cpcie_0/status_engine_3[20]}]
set_property MARK_DEBUG true [get_nets {cpcie_bd_wrapper_i/cpcie_bd_i/scheduler_cpcie_0/status_engine_3[24]}]
set_property MARK_DEBUG true [get_nets {cpcie_bd_wrapper_i/cpcie_bd_i/scheduler_cpcie_0/status_engine_3[30]}]
create_debug_core u_ila_0 ila
set_property ALL_PROBE_SAME_MU true [get_debug_cores u_ila_0]
set_property ALL_PROBE_SAME_MU_CNT 1 [get_debug_cores u_ila_0]
set_property C_ADV_TRIGGER false [get_debug_cores u_ila_0]
set_property C_DATA_DEPTH 4096 [get_debug_cores u_ila_0]
set_property C_EN_STRG_QUAL false [get_debug_cores u_ila_0]
set_property C_INPUT_PIPE_STAGES 0 [get_debug_cores u_ila_0]
set_property C_TRIGIN_EN false [get_debug_cores u_ila_0]
set_property C_TRIGOUT_EN false [get_debug_cores u_ila_0]
set_property port_width 1 [get_debug_ports u_ila_0/clk]
connect_debug_port u_ila_0/clk [get_nets [list cpcie_bd_wrapper_i/cpcie_bd_i/clk_out1]]
set_property port_width 32 [get_debug_ports u_ila_0/probe0]
connect_debug_port u_ila_0/probe0 [get_nets [list {cpcie_bd_wrapper_i/cpcie_bd_i/scheduler_cpcie_0/status_engine_3[0]} {cpcie_bd_wrapper_i/cpcie_bd_i/scheduler_cpcie_0/status_engine_3[1]} {cpcie_bd_wrapper_i/cpcie_bd_i/scheduler_cpcie_0/status_engine_3[2]} {cpcie_bd_wrapper_i/cpcie_bd_i/scheduler_cpcie_0/status_engine_3[3]} {cpcie_bd_wrapper_i/cpcie_bd_i/scheduler_cpcie_0/status_engine_3[4]} {cpcie_bd_wrapper_i/cpcie_bd_i/scheduler_cpcie_0/status_engine_3[5]} {cpcie_bd_wrapper_i/cpcie_bd_i/scheduler_cpcie_0/status_engine_3[6]} {cpcie_bd_wrapper_i/cpcie_bd_i/scheduler_cpcie_0/status_engine_3[7]} {cpcie_bd_wrapper_i/cpcie_bd_i/scheduler_cpcie_0/status_engine_3[8]} {cpcie_bd_wrapper_i/cpcie_bd_i/scheduler_cpcie_0/status_engine_3[9]} {cpcie_bd_wrapper_i/cpcie_bd_i/scheduler_cpcie_0/status_engine_3[10]} {cpcie_bd_wrapper_i/cpcie_bd_i/scheduler_cpcie_0/status_engine_3[11]} {cpcie_bd_wrapper_i/cpcie_bd_i/scheduler_cpcie_0/status_engine_3[12]} {cpcie_bd_wrapper_i/cpcie_bd_i/scheduler_cpcie_0/status_engine_3[13]} {cpcie_bd_wrapper_i/cpcie_bd_i/scheduler_cpcie_0/status_engine_3[14]} {cpcie_bd_wrapper_i/cpcie_bd_i/scheduler_cpcie_0/status_engine_3[15]} {cpcie_bd_wrapper_i/cpcie_bd_i/scheduler_cpcie_0/status_engine_3[16]} {cpcie_bd_wrapper_i/cpcie_bd_i/scheduler_cpcie_0/status_engine_3[17]} {cpcie_bd_wrapper_i/cpcie_bd_i/scheduler_cpcie_0/status_engine_3[18]} {cpcie_bd_wrapper_i/cpcie_bd_i/scheduler_cpcie_0/status_engine_3[19]} {cpcie_bd_wrapper_i/cpcie_bd_i/scheduler_cpcie_0/status_engine_3[20]} {cpcie_bd_wrapper_i/cpcie_bd_i/scheduler_cpcie_0/status_engine_3[21]} {cpcie_bd_wrapper_i/cpcie_bd_i/scheduler_cpcie_0/status_engine_3[22]} {cpcie_bd_wrapper_i/cpcie_bd_i/scheduler_cpcie_0/status_engine_3[23]} {cpcie_bd_wrapper_i/cpcie_bd_i/scheduler_cpcie_0/status_engine_3[24]} {cpcie_bd_wrapper_i/cpcie_bd_i/scheduler_cpcie_0/status_engine_3[25]} {cpcie_bd_wrapper_i/cpcie_bd_i/scheduler_cpcie_0/status_engine_3[26]} {cpcie_bd_wrapper_i/cpcie_bd_i/scheduler_cpcie_0/status_engine_3[27]} {cpcie_bd_wrapper_i/cpcie_bd_i/scheduler_cpcie_0/status_engine_3[28]} {cpcie_bd_wrapper_i/cpcie_bd_i/scheduler_cpcie_0/status_engine_3[29]} {cpcie_bd_wrapper_i/cpcie_bd_i/scheduler_cpcie_0/status_engine_3[30]} {cpcie_bd_wrapper_i/cpcie_bd_i/scheduler_cpcie_0/status_engine_3[31]}]]
create_debug_port u_ila_0 probe
set_property port_width 32 [get_debug_ports u_ila_0/probe1]
connect_debug_port u_ila_0/probe1 [get_nets [list {cpcie_bd_wrapper_i/cpcie_bd_i/scheduler_cpcie_0/status_engine_2[0]} {cpcie_bd_wrapper_i/cpcie_bd_i/scheduler_cpcie_0/status_engine_2[1]} {cpcie_bd_wrapper_i/cpcie_bd_i/scheduler_cpcie_0/status_engine_2[2]} {cpcie_bd_wrapper_i/cpcie_bd_i/scheduler_cpcie_0/status_engine_2[3]} {cpcie_bd_wrapper_i/cpcie_bd_i/scheduler_cpcie_0/status_engine_2[4]} {cpcie_bd_wrapper_i/cpcie_bd_i/scheduler_cpcie_0/status_engine_2[5]} {cpcie_bd_wrapper_i/cpcie_bd_i/scheduler_cpcie_0/status_engine_2[6]} {cpcie_bd_wrapper_i/cpcie_bd_i/scheduler_cpcie_0/status_engine_2[7]} {cpcie_bd_wrapper_i/cpcie_bd_i/scheduler_cpcie_0/status_engine_2[8]} {cpcie_bd_wrapper_i/cpcie_bd_i/scheduler_cpcie_0/status_engine_2[9]} {cpcie_bd_wrapper_i/cpcie_bd_i/scheduler_cpcie_0/status_engine_2[10]} {cpcie_bd_wrapper_i/cpcie_bd_i/scheduler_cpcie_0/status_engine_2[11]} {cpcie_bd_wrapper_i/cpcie_bd_i/scheduler_cpcie_0/status_engine_2[12]} {cpcie_bd_wrapper_i/cpcie_bd_i/scheduler_cpcie_0/status_engine_2[13]} {cpcie_bd_wrapper_i/cpcie_bd_i/scheduler_cpcie_0/status_engine_2[14]} {cpcie_bd_wrapper_i/cpcie_bd_i/scheduler_cpcie_0/status_engine_2[15]} {cpcie_bd_wrapper_i/cpcie_bd_i/scheduler_cpcie_0/status_engine_2[16]} {cpcie_bd_wrapper_i/cpcie_bd_i/scheduler_cpcie_0/status_engine_2[17]} {cpcie_bd_wrapper_i/cpcie_bd_i/scheduler_cpcie_0/status_engine_2[18]} {cpcie_bd_wrapper_i/cpcie_bd_i/scheduler_cpcie_0/status_engine_2[19]} {cpcie_bd_wrapper_i/cpcie_bd_i/scheduler_cpcie_0/status_engine_2[20]} {cpcie_bd_wrapper_i/cpcie_bd_i/scheduler_cpcie_0/status_engine_2[21]} {cpcie_bd_wrapper_i/cpcie_bd_i/scheduler_cpcie_0/status_engine_2[22]} {cpcie_bd_wrapper_i/cpcie_bd_i/scheduler_cpcie_0/status_engine_2[23]} {cpcie_bd_wrapper_i/cpcie_bd_i/scheduler_cpcie_0/status_engine_2[24]} {cpcie_bd_wrapper_i/cpcie_bd_i/scheduler_cpcie_0/status_engine_2[25]} {cpcie_bd_wrapper_i/cpcie_bd_i/scheduler_cpcie_0/status_engine_2[26]} {cpcie_bd_wrapper_i/cpcie_bd_i/scheduler_cpcie_0/status_engine_2[27]} {cpcie_bd_wrapper_i/cpcie_bd_i/scheduler_cpcie_0/status_engine_2[28]} {cpcie_bd_wrapper_i/cpcie_bd_i/scheduler_cpcie_0/status_engine_2[29]} {cpcie_bd_wrapper_i/cpcie_bd_i/scheduler_cpcie_0/status_engine_2[30]} {cpcie_bd_wrapper_i/cpcie_bd_i/scheduler_cpcie_0/status_engine_2[31]}]]
create_debug_port u_ila_0 probe
set_property port_width 32 [get_debug_ports u_ila_0/probe2]
connect_debug_port u_ila_0/probe2 [get_nets [list {cpcie_bd_wrapper_i/cpcie_bd_i/scheduler_cpcie_0/status_engine_0[0]} {cpcie_bd_wrapper_i/cpcie_bd_i/scheduler_cpcie_0/status_engine_0[1]} {cpcie_bd_wrapper_i/cpcie_bd_i/scheduler_cpcie_0/status_engine_0[2]} {cpcie_bd_wrapper_i/cpcie_bd_i/scheduler_cpcie_0/status_engine_0[3]} {cpcie_bd_wrapper_i/cpcie_bd_i/scheduler_cpcie_0/status_engine_0[4]} {cpcie_bd_wrapper_i/cpcie_bd_i/scheduler_cpcie_0/status_engine_0[5]} {cpcie_bd_wrapper_i/cpcie_bd_i/scheduler_cpcie_0/status_engine_0[6]} {cpcie_bd_wrapper_i/cpcie_bd_i/scheduler_cpcie_0/status_engine_0[7]} {cpcie_bd_wrapper_i/cpcie_bd_i/scheduler_cpcie_0/status_engine_0[8]} {cpcie_bd_wrapper_i/cpcie_bd_i/scheduler_cpcie_0/status_engine_0[9]} {cpcie_bd_wrapper_i/cpcie_bd_i/scheduler_cpcie_0/status_engine_0[10]} {cpcie_bd_wrapper_i/cpcie_bd_i/scheduler_cpcie_0/status_engine_0[11]} {cpcie_bd_wrapper_i/cpcie_bd_i/scheduler_cpcie_0/status_engine_0[12]} {cpcie_bd_wrapper_i/cpcie_bd_i/scheduler_cpcie_0/status_engine_0[13]} {cpcie_bd_wrapper_i/cpcie_bd_i/scheduler_cpcie_0/status_engine_0[14]} {cpcie_bd_wrapper_i/cpcie_bd_i/scheduler_cpcie_0/status_engine_0[15]} {cpcie_bd_wrapper_i/cpcie_bd_i/scheduler_cpcie_0/status_engine_0[16]} {cpcie_bd_wrapper_i/cpcie_bd_i/scheduler_cpcie_0/status_engine_0[17]} {cpcie_bd_wrapper_i/cpcie_bd_i/scheduler_cpcie_0/status_engine_0[18]} {cpcie_bd_wrapper_i/cpcie_bd_i/scheduler_cpcie_0/status_engine_0[19]} {cpcie_bd_wrapper_i/cpcie_bd_i/scheduler_cpcie_0/status_engine_0[20]} {cpcie_bd_wrapper_i/cpcie_bd_i/scheduler_cpcie_0/status_engine_0[21]} {cpcie_bd_wrapper_i/cpcie_bd_i/scheduler_cpcie_0/status_engine_0[22]} {cpcie_bd_wrapper_i/cpcie_bd_i/scheduler_cpcie_0/status_engine_0[23]} {cpcie_bd_wrapper_i/cpcie_bd_i/scheduler_cpcie_0/status_engine_0[24]} {cpcie_bd_wrapper_i/cpcie_bd_i/scheduler_cpcie_0/status_engine_0[25]} {cpcie_bd_wrapper_i/cpcie_bd_i/scheduler_cpcie_0/status_engine_0[26]} {cpcie_bd_wrapper_i/cpcie_bd_i/scheduler_cpcie_0/status_engine_0[27]} {cpcie_bd_wrapper_i/cpcie_bd_i/scheduler_cpcie_0/status_engine_0[28]} {cpcie_bd_wrapper_i/cpcie_bd_i/scheduler_cpcie_0/status_engine_0[29]} {cpcie_bd_wrapper_i/cpcie_bd_i/scheduler_cpcie_0/status_engine_0[30]} {cpcie_bd_wrapper_i/cpcie_bd_i/scheduler_cpcie_0/status_engine_0[31]}]]
create_debug_port u_ila_0 probe
set_property port_width 32 [get_debug_ports u_ila_0/probe3]
connect_debug_port u_ila_0/probe3 [get_nets [list {cpcie_bd_wrapper_i/cpcie_bd_i/scheduler_cpcie_0/status_engine_1[0]} {cpcie_bd_wrapper_i/cpcie_bd_i/scheduler_cpcie_0/status_engine_1[1]} {cpcie_bd_wrapper_i/cpcie_bd_i/scheduler_cpcie_0/status_engine_1[2]} {cpcie_bd_wrapper_i/cpcie_bd_i/scheduler_cpcie_0/status_engine_1[3]} {cpcie_bd_wrapper_i/cpcie_bd_i/scheduler_cpcie_0/status_engine_1[4]} {cpcie_bd_wrapper_i/cpcie_bd_i/scheduler_cpcie_0/status_engine_1[5]} {cpcie_bd_wrapper_i/cpcie_bd_i/scheduler_cpcie_0/status_engine_1[6]} {cpcie_bd_wrapper_i/cpcie_bd_i/scheduler_cpcie_0/status_engine_1[7]} {cpcie_bd_wrapper_i/cpcie_bd_i/scheduler_cpcie_0/status_engine_1[8]} {cpcie_bd_wrapper_i/cpcie_bd_i/scheduler_cpcie_0/status_engine_1[9]} {cpcie_bd_wrapper_i/cpcie_bd_i/scheduler_cpcie_0/status_engine_1[10]} {cpcie_bd_wrapper_i/cpcie_bd_i/scheduler_cpcie_0/status_engine_1[11]} {cpcie_bd_wrapper_i/cpcie_bd_i/scheduler_cpcie_0/status_engine_1[12]} {cpcie_bd_wrapper_i/cpcie_bd_i/scheduler_cpcie_0/status_engine_1[13]} {cpcie_bd_wrapper_i/cpcie_bd_i/scheduler_cpcie_0/status_engine_1[14]} {cpcie_bd_wrapper_i/cpcie_bd_i/scheduler_cpcie_0/status_engine_1[15]} {cpcie_bd_wrapper_i/cpcie_bd_i/scheduler_cpcie_0/status_engine_1[16]} {cpcie_bd_wrapper_i/cpcie_bd_i/scheduler_cpcie_0/status_engine_1[17]} {cpcie_bd_wrapper_i/cpcie_bd_i/scheduler_cpcie_0/status_engine_1[18]} {cpcie_bd_wrapper_i/cpcie_bd_i/scheduler_cpcie_0/status_engine_1[19]} {cpcie_bd_wrapper_i/cpcie_bd_i/scheduler_cpcie_0/status_engine_1[20]} {cpcie_bd_wrapper_i/cpcie_bd_i/scheduler_cpcie_0/status_engine_1[21]} {cpcie_bd_wrapper_i/cpcie_bd_i/scheduler_cpcie_0/status_engine_1[22]} {cpcie_bd_wrapper_i/cpcie_bd_i/scheduler_cpcie_0/status_engine_1[23]} {cpcie_bd_wrapper_i/cpcie_bd_i/scheduler_cpcie_0/status_engine_1[24]} {cpcie_bd_wrapper_i/cpcie_bd_i/scheduler_cpcie_0/status_engine_1[25]} {cpcie_bd_wrapper_i/cpcie_bd_i/scheduler_cpcie_0/status_engine_1[26]} {cpcie_bd_wrapper_i/cpcie_bd_i/scheduler_cpcie_0/status_engine_1[27]} {cpcie_bd_wrapper_i/cpcie_bd_i/scheduler_cpcie_0/status_engine_1[28]} {cpcie_bd_wrapper_i/cpcie_bd_i/scheduler_cpcie_0/status_engine_1[29]} {cpcie_bd_wrapper_i/cpcie_bd_i/scheduler_cpcie_0/status_engine_1[30]} {cpcie_bd_wrapper_i/cpcie_bd_i/scheduler_cpcie_0/status_engine_1[31]}]]
set_property C_CLK_INPUT_FREQ_HZ 300000000 [get_debug_cores dbg_hub]
set_property C_ENABLE_CLK_DIVIDER false [get_debug_cores dbg_hub]
set_property C_USER_SCAN_CHAIN 1 [get_debug_cores dbg_hub]
connect_debug_port dbg_hub/clk [get_nets u_ila_0_clk_out1]
