webtalk_init -webtalk_dir C:\\mohd\\cpcie\\test_xillybus_mb_4mD\\cpcie.sdk\\webtalk
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Thu Apr 27 14:25:06 2017" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "SDK v2014.4" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2014.4" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "amd64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "175311095_202152274_210573551_724" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "SDK" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "false" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "ub0qflr8uod1cvdpafipu5fsfe" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "2014.4_94" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "94" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Microsoft Windows 7 , 64-bit" -context "user_environment"
webtalk_add_data -client project -key os_release -value "Service Pack 1  (build 7601)" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "Intel(R) Xeon(R) CPU           E5520  @ 2.27GHz" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "2266 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "6.000 GB" -context "user_environment"
webtalk_register_client -client sdk
webtalk_add_data -client sdk -key uid -value "1493299216072" -context "sdk\\\\hardware/1493299216072"
webtalk_add_data -client sdk -key isZynq -value "false" -context "sdk\\\\hardware/1493299216072"
webtalk_add_data -client sdk -key Processors -value "1" -context "sdk\\\\hardware/1493299216072"
webtalk_add_data -client sdk -key VivadoVersion -value "2014.4" -context "sdk\\\\hardware/1493299216072"
webtalk_add_data -client sdk -key Arch -value "virtex7" -context "sdk\\\\hardware/1493299216072"
webtalk_add_data -client sdk -key Device -value "7vx485t" -context "sdk\\\\hardware/1493299216072"
webtalk_add_data -client sdk -key IsHandoff -value "true" -context "sdk\\\\hardware/1493299216072"
webtalk_add_data -client sdk -key uid -value "1493299228712" -context "sdk\\\\bsp/1493299228712"
webtalk_add_data -client sdk -key hwid -value "1493299216072" -context "sdk\\\\bsp/1493299228712"
webtalk_add_data -client sdk -key os -value "standalone" -context "sdk\\\\bsp/1493299228712"
webtalk_add_data -client sdk -key apptemplate -value "hello_world" -context "sdk\\\\bsp/1493299228712"
webtalk_add_data -client sdk -key uid -value "1493299235694" -context "sdk\\\\application/1493299235694"
webtalk_add_data -client sdk -key hwid -value "1493299216072" -context "sdk\\\\application/1493299235694"
webtalk_add_data -client sdk -key bspid -value "1493299228712" -context "sdk\\\\application/1493299235694"
webtalk_add_data -client sdk -key newbsp -value "true" -context "sdk\\\\application/1493299235694"
webtalk_add_data -client sdk -key os -value "standalone" -context "sdk\\\\application/1493299235694"
webtalk_add_data -client sdk -key apptemplate -value "hello_world" -context "sdk\\\\application/1493299235694"
webtalk_transmit -clientid 4075543671 -regid "175311095_202152274_210573551_724" -xml C:\\mohd\\cpcie\\test_xillybus_mb_4mD\\cpcie.sdk\\webtalk\\usage_statistics_ext_sdk.xml -html C:\\mohd\\cpcie\\test_xillybus_mb_4mD\\cpcie.sdk\\webtalk\\usage_statistics_ext_sdk.html -wdm C:\\mohd\\cpcie\\test_xillybus_mb_4mD\\cpcie.sdk\\webtalk\\sdk_webtalk.wdm -intro "<H3>SDK Usage Report</H3><BR>"
webtalk_terminate
