// ==============================================================
// File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2013.3
// Copyright (C) 2013 Xilinx Inc. All rights reserved.
// 
// ==============================================================

#ifndef XMATRIXMUL_ACCEL_CORE_H
#define XMATRIXMUL_ACCEL_CORE_H

#ifdef __cplusplus
extern "C" {
#endif

/***************************** Include Files *********************************/
#ifndef __linux__
#include "xil_types.h"
#include "xil_assert.h"
#include "xstatus.h"
#include "xil_io.h"
#else
#include <stdint.h>
#include <assert.h>
#include <dirent.h>
#include <fcntl.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <sys/mman.h>
#include <unistd.h>
#include <stddef.h>
#endif
#include "xmatrixmul_accel_core_hw.h"

/**************************** Type Definitions ******************************/
#ifdef __linux__
typedef uint8_t u8;
typedef uint16_t u16;
typedef uint32_t u32;
#else
typedef struct {
    u16 DeviceId;
    u32 Control_bus_BaseAddress;
} XMatrixmul_accel_core_Config;
#endif

typedef struct {
    u32 Control_bus_BaseAddress;
    u32 IsReady;
} XMatrixmul_accel_core;

/***************** Macros (Inline Functions) Definitions *********************/
#ifndef __linux__
#define XMatrixmul_accel_core_WriteReg(BaseAddress, RegOffset, Data) \
    Xil_Out32((BaseAddress) + (RegOffset), (u32)(Data))
#define XMatrixmul_accel_core_ReadReg(BaseAddress, RegOffset) \
    Xil_In32((BaseAddress) + (RegOffset))
#else
#define XMatrixmul_accel_core_WriteReg(BaseAddress, RegOffset, Data) \
    *(volatile u32*)((BaseAddress) + (RegOffset)) = (u32)(Data)
#define XMatrixmul_accel_core_ReadReg(BaseAddress, RegOffset) \
    *(volatile u32*)((BaseAddress) + (RegOffset))

#define Xil_AssertVoid(expr)    assert(expr)
#define Xil_AssertNonvoid(expr) assert(expr)

#define XST_SUCCESS             0
#define XST_DEVICE_NOT_FOUND    2
#define XST_OPEN_DEVICE_FAILED  3
#define XIL_COMPONENT_IS_READY  1
#endif

/************************** Function Prototypes *****************************/
#ifndef __linux__
int XMatrixmul_accel_core_Initialize(XMatrixmul_accel_core *InstancePtr, u16 DeviceId);
XMatrixmul_accel_core_Config* XMatrixmul_accel_core_LookupConfig(u16 DeviceId);
int XMatrixmul_accel_core_CfgInitialize(XMatrixmul_accel_core *InstancePtr, XMatrixmul_accel_core_Config *ConfigPtr);
#else
int XMatrixmul_accel_core_Initialize(XMatrixmul_accel_core *InstancePtr, const char* InstanceName);
int XMatrixmul_accel_core_Release(XMatrixmul_accel_core *InstancePtr);
#endif

void XMatrixmul_accel_core_Start(XMatrixmul_accel_core *InstancePtr);
u32 XMatrixmul_accel_core_IsDone(XMatrixmul_accel_core *InstancePtr);
u32 XMatrixmul_accel_core_IsIdle(XMatrixmul_accel_core *InstancePtr);
u32 XMatrixmul_accel_core_IsReady(XMatrixmul_accel_core *InstancePtr);
void XMatrixmul_accel_core_EnableAutoRestart(XMatrixmul_accel_core *InstancePtr);
void XMatrixmul_accel_core_DisableAutoRestart(XMatrixmul_accel_core *InstancePtr);


void XMatrixmul_accel_core_InterruptGlobalEnable(XMatrixmul_accel_core *InstancePtr);
void XMatrixmul_accel_core_InterruptGlobalDisable(XMatrixmul_accel_core *InstancePtr);
void XMatrixmul_accel_core_InterruptEnable(XMatrixmul_accel_core *InstancePtr, u32 Mask);
void XMatrixmul_accel_core_InterruptDisable(XMatrixmul_accel_core *InstancePtr, u32 Mask);
void XMatrixmul_accel_core_InterruptClear(XMatrixmul_accel_core *InstancePtr, u32 Mask);
u32 XMatrixmul_accel_core_InterruptGetEnabled(XMatrixmul_accel_core *InstancePtr);
u32 XMatrixmul_accel_core_InterruptGetStatus(XMatrixmul_accel_core *InstancePtr);

#ifdef __cplusplus
}
#endif

#endif
